[workspace]
members = [
    "packages/wry-launch",
    "packages/wry-bindgen-core",
    "packages/wry-bindgen",
    "packages/wry-bindgen-runtime",
    "packages/wry-bindgen-macro",
    "packages/wry-bindgen-macro-support",
    "packages/wasm-bindgen",
    "packages/wasm-bindgen-macro",
    "packages/js-sys-x",
    "packages/web-sys-x",
    "packages/wasm-bindgen-futures-x",
    "packages/wasm-bindgen-test",
    "packages/wasm-bindgen-test-macro",
    "examples/gloo",
    "examples/dioxus-web",
    "examples/yew",
    "examples/leptos",
    "examples/piet",
    "examples/tiptap",
    "examples/openstreetmap"
]
exclude = ["vendored/wasm-bindgen"]
resolver = "2"

[patch.crates-io]
wasm-bindgen = { path = "packages/wasm-bindgen", package = "wasm-bindgen" }
js-sys = { path = "packages/js-sys-x", package = "js-sys-x" }
web-sys = { path = "packages/web-sys-x", package = "web-sys-x" }
wasm-bindgen-futures = { path = "packages/wasm-bindgen-futures-x", package = "wasm-bindgen-futures-x" }

[workspace.lints]
